### ISSUE TITLE
Broken on 14.2 beta2 (default version)

### ISSUE THREAD

**Issue by f1vefour** [xbianonpi/xbian-package-config-xbmc#29]
* See forum thread: http://forum.xbian.org/showthread.php?tid=2811
* Log from user: http://pastebin.com/CzwFdDja

> D-Kalck
I did a fresh install of Xbian and when I launch Xbian Config from within Kodi (around line 1194 in the log file), it loads until around 25% and close.

**Comment by mk01** [comment]
@f1vefour 

this is solved 7034239ae4a2f05640cc08a089ef3593167f0a9c
(90% sure)

that means the next image should be OK.

**Comment by mk01** [comment]
just retested youtube and all ok, so lets do the native recompile against jessie with older curl. if imx6, there is no reason rpi not to.

**Comment by D-Kalck** [comment]
I have version xbian-package-config-xbmc 20150306-0 but I still have the problem.
And I confirm I have the right cache directory  :
CACHEDIR = '/home/xbian/.kodi/userdata/addon_data/plugin.xbianconfig'

**Comment by mk01** [comment]
@D-Kalck 

can you edit file:
```
/usr/local/include/xbian-config/modules/packages/main 
```
line 220, and change
```
packages-success-stamp 
=>
update--success-stamp
```

and report back?
(basically this commit)
https://github.com/xbianonpi/xbian-package-config-shell/commit/eacd1a1e7e4a7f9037935860cabee5c30b1cb5d3

**Comment by D-Kalck** [comment]
Yes, it works now !
Thank you.
